[workspace]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["https://prefix.dev/conda-forge"]
name = "lockfile-test"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
test-lockfile = { cmd = "python test_lockfile.py", env = { PIXI_CACHE_DIR = "pixi-cache" } }

[feature.source.dependencies]
pixi-package = { path = "pixi-package" }

[environments]
source = ["source"]